package clases;
// Generated 7 dic 2024, 18:57:49 by Hibernate Tools 5.4.33.Final

/**
 * TTrenes generated by hbm2java
 */
public class TTrenes implements java.io.Serializable {

	private int codTren;
	private TLineas TLineas;
	private TCocheras TCocheras;
	private String nombre;
	private String tipo;

	public TTrenes() {
	}

	public TTrenes(int codTren, TLineas TLineas, TCocheras TCocheras, String nombre, String tipo) {
		this.codTren = codTren;
		this.TLineas = TLineas;
		this.TCocheras = TCocheras;
		this.nombre = nombre;
		this.tipo = tipo;
	}

	public int getCodTren() {
		return this.codTren;
	}

	public void setCodTren(int codTren) {
		this.codTren = codTren;
	}

	public TLineas getTLineas() {
		return this.TLineas;
	}

	public void setTLineas(TLineas TLineas) {
		this.TLineas = TLineas;
	}

	public TCocheras getTCocheras() {
		return this.TCocheras;
	}

	public void setTCocheras(TCocheras TCocheras) {
		this.TCocheras = TCocheras;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
