package clases;
// Generated 9 dic 2024, 16:54:27 by Hibernate Tools 5.5.9.Final

/**
 * TNuevos2 generated by hbm2java
 */
public class TNuevos2 implements java.io.Serializable {

	private int codTren;
	private String nombre;
	private String tipo;
	private int codLinea;
	private int codCochera;

	public TNuevos2() {
	}

	public TNuevos2(int codTren, String nombre, String tipo, int codLinea, int codCochera) {
		this.codTren = codTren;
		this.nombre = nombre;
		this.tipo = tipo;
		this.codLinea = codLinea;
		this.codCochera = codCochera;
	}

	public int getCodTren() {
		return this.codTren;
	}

	public void setCodTren(int codTren) {
		this.codTren = codTren;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	public int getCodCochera() {
		return this.codCochera;
	}

	public void setCodCochera(int codCochera) {
		this.codCochera = codCochera;
	}

}
