package clases;
// Generated 9 dic 2024, 16:19:36 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;

/**
 * Nuevos generated by hbm2java
 */
public class Nuevos implements java.io.Serializable {

	private BigInteger deptNo;
	private String dnombre;
	private String loc;

	public Nuevos() {
	}

	public Nuevos(BigInteger deptNo) {
		this.deptNo = deptNo;
	}

	public Nuevos(BigInteger deptNo, String dnombre, String loc) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
	}

	public BigInteger getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(BigInteger deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

}
